#ifndef OPTIONS_H
#define OPTIONS_H

#include <cstddef>

namespace yundb
{

class Comparator;
class Env;
class FilterPolicy;
class Snapshot;
class Logger;

enum CompressionType
{
  SnappyCompression = 0x0,
  NoCompression = 0x1,
};

struct Options
{
  Options();
  // used to define the order of keys in the table.
  // Default: a comparator that uses lexicographic byte-wise ordering
  const Comparator* comparator;
  // Any internal progress/error information generated by the db will
  // be written to info_log if it is non-null, or to a file stored
  // in the same directory as the DB contents if info_log is null.
  const Logger* info_log = nullptr;

  // If non-null, use the specified filter policy to reduce disk reads.
  // default use the bloom filter
  const FilterPolicy* filter_policy;

  // If true, the database will be created if it is missing.
  bool create_if_missing = false;

  // If true, an error is raised if the database already exists.
  bool error_if_exists = false;

  // Use the specified object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  // Default: Env::Default()
  Env* env;

  // Amount of data to build up in memory (backed by an unsorted log
  // on disk) before converting to a sorted on-disk file.
  size_t write_buffer_size = 4 * 1024 * 1024;

  // Approximate size of user data packed per block.
  size_t block_size = 4 * 1024;

  // Write up to this amount of bytes to a file before
  // switching to a new one.
  size_t max_file_size = 2 * 1024 * 1024;

  // Number of open files that can be used by the DB.
  int max_open_file = 1000;

  // Number of keys between restart points for delta encoding of keys.
  int block_restart_interval = 16;

  // Use google Snappy compression
  CompressionType compression = SnappyCompression;
};

// Options that control read operations
struct ReadOptions
{
  // If true, all data read from underlying storage will be
  // verified against corresponding checksums.
  bool verify_checksums = false;

  // Should the data read for this iteration be cached in memory?
  // Callers may wish to set this field to false for bulk scans.
  bool fill_cache = true;

  // If "snapshot" is non-null, read as of the supplied snapshot
  // (which must belong to the DB that is being read and which must
  // not have been released).  If "snapshot" is null, use an implicit
  // snapshot of the state at the beginning of this read operation.
  const Snapshot* snapshot = nullptr;
};

// Options that control write operations
struct WriteOptions
{
  WriteOptions() = default;

  // If true, the write will be flushed from the operating system
  // buffer cache (by calling WritableFile::Sync()) before the write
  // is considered complete.  If this flag is true, writes will be
  // slower.
  //
  // If this flag is false, and the machine crashes, some recent
  // writes may be lost.  Note that if it is just the process that
  // crashes (i.e., the machine does not reboot), no writes will be
  // lost even if sync==false.
  //
  // In other words, a DB write with sync==false has similar
  // crash semantics as the "write()" system call.  A DB write
  // with sync==true has similar crash semantics to a "write()"
  // system call followed by "fsync()".
  bool sync = false;
};

}

#endif